# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190925_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexad',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
